spring:
  jackson:
    dateFormat: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Tokyo
# References
# - [spring-actuator-example/application.yml at master · indrabasak/spring-actuator-example](https://github.com/indrabasak/spring-actuator-example/blob/master/src/main/resources/application.yml#L8)
